name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: sudo apt-get install gcc-mingw-w64 -y
    - name: build 
      run: ./build-for-windows.sh
