name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Upload artitact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup
        run: sudo apt-get install gcc-mingw-w64 -y
      - name: build for windows 
        run: ./build-for-windows.sh
      - name: build for linux
        run: ./build-for-linux.sh
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build/ # or path/to/artifact
